global using Carter;
global using Mapster;
global using MediatR;
global using Marten;
global using BuildingBlocks.CQRS;
global using Catalog.Models;
global using Catalog.Exceptions;
global using FluentValidation;
global using FluentValidation.AspNetCore;